### ISSUE TITLE
PFData constructor with numpy array issues

### ISSUE THREAD

**Issue by arezaii** [hydroframe/parflowio#7]
When assigning a large numpy array as the data member using the PFData(<array>) constructor results in a segfault when writing the data to disk.

**Steps to Reproduce:**
```
import numpy as np
from parflowio.pyParflowio import PFData
large_data = np.random.rand(16, 4600, 7600)
pfdata = PFData(large_data.astype(np.float64))
pfdata.writeFile('large_output.pfb')
```

**Actual Results:**
Segfault

**Expected Results:**
pfb file written to disk

**Other notes:**
If you instead construct the PFData object with the default constructor, then assign the same large data array using setDataArray(<array>), the write operation works as expected:
```
import numpy as np
from parflowio.pyParflowio import PFData
large_data = np.random.rand(16, 4600, 7600)
pfdata = PFData()
pfdata.setDataArray(large_data.astype(np.float64))
pfdata.writeFile('large_output.pfb')
```

**Comment by jaredwhite547** [comment]
Fixed. Note, instead of doing `PFData(large_data.astype(np.float64))`, just do `PFData(large_data)`
